name: Run Tests

on: 
  pull_request: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '18.9'
      - name: NPM Install
        run: | 
          npm ci
      - name: Tests
        run: |
          npm run test