name: React Deploy

on: 
  push: 
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.x]

    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '18.9'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          envkey_USER_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          envkey_APP_DOMAIN: "cortes-debt.com"
          envkey_API_ROOT: "api.cortes-debt.com"
          file_name: .env.production
          fail_on_empty: true
      - name: NPM Install
        run: | 
          npm ci
      - name: Tests
        run: |
          npm run test
      - name: NPM build
        run: |
          npm run build --if-present
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "dist"